-- Business Social Media Health Check — run once in the Supabase SQL editor.

create table if not exists public.assessment_submissions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),

  -- Idempotency key generated by the browser; a refresh/double-click can never insert twice.
  submission_key uuid not null unique,

  name text not null check (char_length(name) between 2 and 120),
  email text not null check (char_length(email) between 5 and 254 and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  business_name text not null check (char_length(business_name) between 2 and 160),
  phone text not null check (char_length(phone) between 7 and 30),

  q1_answer text not null, q1_score smallint not null check (q1_score in (6, 8, 10)),
  q2_answer text not null, q2_score smallint not null check (q2_score in (4, 6, 8, 10)),
  q3_answer text not null, q3_score smallint not null check (q3_score in (4, 6, 8, 10)),
  q4_answer text not null, q4_score smallint not null check (q4_score in (4, 6, 8, 10)),
  q5_answer text not null, q5_score smallint not null check (q5_score in (4, 6, 8, 10)),
  q6_answer text not null, q6_score smallint not null check (q6_score in (4, 6, 8, 10)),
  q7_answer text not null, q7_score smallint not null check (q7_score in (4, 6, 8, 10)),
  q8_answer text not null, q8_score smallint not null check (q8_score in (4, 6, 8, 10)),
  q9_answer text not null, q9_score smallint not null check (q9_score in (4, 6, 8, 10)),
  q10_answer text not null, q10_score smallint not null check (q10_score in (4, 6, 8, 10)),

  total_score smallint not null check (total_score between 42 and 100),
  percentage_score smallint not null check (percentage_score between 0 and 100),
  health_level text not null,

  strategy_score smallint not null check (strategy_score between 0 and 100),
  consistency_score smallint not null check (consistency_score between 0 and 100),
  audience_score smallint not null check (audience_score between 0 and 100),
  business_impact_score smallint not null check (business_impact_score between 0 and 100),
  strongest_dimension text not null,
  weakest_dimension text not null,

  generated_diagnosis text not null,
  generated_strengths jsonb not null default '[]'::jsonb,
  generated_weaknesses jsonb not null default '[]'::jsonb,
  generated_recommendations jsonb not null default '[]'::jsonb
);

create index if not exists assessment_submissions_created_at_idx
  on public.assessment_submissions (created_at desc);
create index if not exists assessment_submissions_total_score_idx
  on public.assessment_submissions (total_score);

-- Lock the table down. No policies are created, so the public anon key and
-- signed-in users cannot read or write anything. The app talks to this table
-- only from the server, using the service-role key (which bypasses RLS).
alter table public.assessment_submissions enable row level security;
revoke all on public.assessment_submissions from anon, authenticated;

-- Dashboard summary numbers, computed in the database.
create or replace function public.assessment_stats()
returns json
language sql
stable
as $$
  select json_build_object(
    'total', count(*),
    'average', coalesce(round(avg(total_score)::numeric, 1), 0),
    'this_month', count(*) filter (where created_at >= date_trunc('month', now())),
    'strong', count(*) filter (where total_score >= 86),
    'good', count(*) filter (where total_score between 71 and 85),
    'active', count(*) filter (where total_score between 56 and 70),
    'reactive', count(*) filter (where total_score <= 55)
  )
  from public.assessment_submissions;
$$;

revoke execute on function public.assessment_stats() from public, anon, authenticated;
grant execute on function public.assessment_stats() to service_role;
